default.timeout=30
application.url=https://www.premiobomgourmet.com.br/

# If nothing is passed, chrome will be used
browser=

fullName=Filipe Gomes
email=filipinho_28@hotmail.com
place=Mornings Cabral
city=Curitiba
